services:
  postgres:
    image: postgres:16
    container_name: viajesjmj_postgres
    environment:
      POSTGRES_DB: viajesjmj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - viajesjmj_postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: viajesjmj_backend
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://postgres:5432/viajesjmj
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CORS_ALLOWED_ORIGINS: http://localhost:4200
      UNSPLASH_ACCESS_KEY: "82rh8QWXmUMQ0ve3ouLd8SBu8aRkEBzt9ICqS1RL_3c"
    ports:
      - "8081:8080"

volumes:
  viajesjmj_postgres_data: