spring.application.name=viajesJMJ

server.port=${PORT:8081}

# POSTGRESQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/viajesjmj}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CARGAR DATA.SQL SOLO EN EL PRIMER ARRANQUE
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,https://juanan-jmjviajes.qu3v3d0.tech}

# UNSPLASH
unsplash.access.key=${UNSPLASH_ACCESS_KEY:TU_CLAVE_LOCAL}