spring.application.name=viajesJMJ

server.port=${PORT:8081}

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/viajesjmj}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# No ejecutar data.sql automáticamente
spring.sql.init.mode=never

# CORS frontend Angular
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://juanan.qu3v3d0.tech,https://juanan.qu3v3d0.tech}

# Unsplash
unsplash.access.key=${UNSPLASH_ACCESS_KEY:}