spring.application.name=viajesJMJ

spring.datasource.url=jdbc:mysql://localhost:3306/viajesjmj
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

unsplash.access.key=82rh8QWXmUMQ0ve3ouLd8SBu8aRkEBzt9ICqS1RL_3c